# Generated by Django 3.2.16 on 2023-01-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='Applied',
            field=models.BooleanField(default=False),
        ),
    ]
