# Generated by Django 3.2.16 on 2023-01-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_attendant_applied'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveApply',
        ),
    ]
