# Generated by Django 3.2.16 on 2023-01-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_delete_leaveapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberID', models.IntegerField()),
                ('Start', models.DateTimeField()),
                ('End', models.DateTimeField()),
                ('Info', models.TextField()),
                ('Applied', models.BooleanField(default=False)),
            ],
        ),
    ]
