# Generated by Django 3.2.15 on 2023-01-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_delete_attendant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberID', models.IntegerField()),
                ('Start', models.DateTimeField()),
                ('End', models.DateTimeField()),
                ('Info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberID', models.IntegerField()),
                ('CheckIn', models.BooleanField(default=False)),
                ('StartTime', models.DateTimeField()),
            ],
        ),
    ]
