# Generated by Django 3.2.16 on 2023-01-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_attendant_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='Info',
            field=models.TextField(default=''),
        ),
    ]
