# Generated by Django 3.2.16 on 2023-01-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_attendant_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='StartTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
